

-----
spring.application.name=flowpolicy

server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/flowpolicy_db

flowpolicy.jwt.secret=MiClaveSuperSecretaParaFlowPolicy2026Segura
flowpolicy.jwt.expiration=86400000

flowpolicy.ia.url=http://localhost:8001

management.endpoints.web.exposure.include=health,info