

spring.application.name=flowpolicy

server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/flowpolicy_db

# JWT (min 32 chars)
flowpolicy.jwt.secret=MiClaveSuperSecretaParaFlowPolicy2026Segura
flowpolicy.jwt.expiration=86400000

# Actuator
management.endpoints.web.exposure.include=health,info

# Springdoc / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# Seeder
app.seeder.startup-enabled=true

# CORS
app.cors.allowed-origin=http://localhost:4200